### ISSUE TITLE
Create Dummy Library for xHPTDC8

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#1]
Create a dummy library that can be used to develop code for the [xHPTDC8](https://www.cronologic.de/products/tdcs/xhptdc8-pcie)

More details are in the [README.md] (https://github.com/cronologic-de/xhptdc8_babel/tree/main/dummy/README.md)

**Comment by Bassem-Ramzy** [comment]
Created on .\dummy sub folder

**Comment by Bassem-Ramzy** [comment]
@sulimma 
Is this a valid assumption ?
> Only one device is supported in the Dummy Library, so, index should be always 0

```C
crono_bool_t _xhptdc8_is_valid_device_index_inernal(xhptdc8_manager hMgr, int index)
{
	if (!xhptdc8_is_valid_manager(hMgr))
		return false;

	if (0 != index )
	{
		// No need to set the last error message, as XHPTDC8_INVALID_ARGUMENTS 
		// should be returned by the caller
		return false;
	}
	return true;
}
``

**Comment by sulimma** [comment]
The current version of the dummy library can't be configured so it always has a fixed number of boards (one board).
So it is correct in this version.

However,  I believe that a better implementation would be to the the number of devices to 1 somewhere and check against that value in this function.
