### ISSUE TITLE
Compilation error in xHPTDC8_interface.h, xhptdc8_grouping_configuration

### ISSUE THREAD

**Issue by Bassem-Ramzy** [cronologic-de/xhptdc8_babel#11]
xHPTDC8_interface.h file generates the following compilation error on both MS Visual Studio 2019 Client, and MSBuild on github action:
> error C5208: unnamed class used in typedef name cannot declare members other than non-static data members, member enumerations, or member classes
The checked in solution is to do

```C
typedef struct xhptdc8_grouping_configuration_ xhptdc8_grouping_configuration;
	struct xhptdc8_grouping_configuration_ {
        .
        .
        };
```

instead of:

```C
	typedef struct {
        .
        .
        } xhptdc8_grouping_configuration;
```

**Comment by Bassem-Ramzy** [comment]
Log of  the build & error is found [here](https://github.com/cronologic-de/xhptdc8_babel/runs/2143331328?check_suite_focus=true)

**Comment by sulimma** [comment]
I currently don't have a compiler here, but I believe that the default assignment in this line is the problem:
bool enabled = false;

I think you need to change it to
crono_bool_t enabled; 

and initialize it when the the other members are initialized.
I file an issue with the developers.

**Comment by Bassem-Ramzy** [comment]
Applied
