### ISSUE TITLE
UG vs Code

### ISSUE THREAD

**Issue by Bassem-Ramzy** [cronologic-de/xhptdc8_babel#15]
There is a difference between **trigger_threshold** definition in User Guide and that in the code

User Guide
>  double threshold[XHPTDC8_TDC_CHANNEL_COUNT + 1]

Code:
```C
double trigger_threshold[XHPTDC8_TDC_CHANNEL_COUNT];
```

Need to unify both:
1. The name
2. The array size

________

"xhptdc8_adc_channel" is missing in the User Guide, while referred to in the code example 
> mgr_cfg−>device_configs[device_index].adc_channel....

_______

**Comment by sulimma** [comment]
Thank you. 
The code is correct. I move this issue to the user guide project.

**Comment by Bassem-Ramzy** [comment]
There is a difference in variables names in structure **xhptdc8_device_configuration**, that have prefix **xhptdc8_** in User Guide, e.g. _xhptdc8_trigger_.

User Guide

> xhptdc8_trigger xhptdc8_trigger[XHPTDC8_TRIGGER_COUNT]

Code
```C
xhptdc8_trigger trigger[XHPTDC8_TRIGGER_COUNT];
```
Need to unify:
- The name

**Comment by Bassem-Ramzy** [comment]
1.

In interface.h: 
```C
crono_bool_t veto_mode;
```

It should be 
```C
int veto_mode;
```
to comply with XHPTDC8_GROUPING_VETO_OUTSIDE = 2

**Comment by Bassem-Ramzy** [comment]
2.

```C
double threshold[XHPTDC8_TDC_CHANNEL_COUNT]
```

Should be 
```C
double threshold[XHPTDC8_TDC_CHANNEL_COUNT + 1]
```

**Comment by sulimma** [comment]
I did all these corrections in the user guide and will push them shortly.
