### ISSUE TITLE
For YAML support, manager structure ALL members to have "default values"

### ISSUE THREAD

**Issue by Bassem-Ramzy** [cronologic-de/xhptdc8_babel#16]
To make it easier for the user, we need to make sure that both the Driver and Dummy Library provide a default value for every member of the manager structure

Related to issue: Load xhptdc8_manager_configuration from YAML #4

**Comment by sulimma** [comment]
This is implemented.  get_default_configuration will always return a filled structure.

The intended process is:

```C++
xhptdc8_get_default_configuration(xhptdc8_man, mgr_cfg);
xhptdc8_apply_yaml_to_configuration(mgr_cfg, yaml_string1);
xhptdc8_apply_yaml_to_configuration(mgr_cfg, yaml_string2);
xhptdc8_configure(xhptdc8_man, mgr_cfg);
```
