### ISSUE TITLE
Info-Tool

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#19]
#xhptdc8_info.exe 

This shall be a programm that provides human readable output on the TDCs available in the system. 

## extensions to the util library
First for each info call in the API there shall be a method in the util library printing the structure it returns. For example `xhptdc8_print_fast_info(xhptdc8_fast_info info, crono_bool_t show_version)`.

## output format for library functions
**Go has support to print structures. Let us try this first. If it is looking good we use it. Otherwise apply the specification below.**

The output shall be a table with the values in the first column and the name of the structure member in the second column. 

The columns shall be seperated by a `=` in position 8. 

If `show_version` is true, the size and version fields are printed, otherwise they are omitted. On the command line this is controlled usin the `-v` switch.

Numbers shall be aligned according to the digit value. There shall be three positions for integers, one dot and two positions for fractions. Numbers shall be rounded to two digits before printing.  Format String %6.2f, also for integers.

Arrays shall be printed with one line per entry.

###Example for `xhptdc8_temperature_info` with -v: 
```
 24    = size
  1    = version
 67.12 = tdc[0]
 63.91 = tdc[1]
```

##output format for command line tool
The command line tool prints a line with the name of the structure the serial number and the board index before printing the output of the library function
```
fast_info of xHPTDC8 serial 21.108 at index 1:
```
### choosing which TDC to print
By default all xHPTDC8 are listed, sorted by serial number.
The first command line parameter can be either an integer or a serial number. If it is an integer, only the TDC with that index will be printed. If it is a serial number only the TDC with that serial number is printed. 

### choosing what information to print
If no command line switch is printed, only `static_info` is printed.
If there is at least one command line switch, only the selected structures are printed. 
```
-v            show size and version information for all selected structures
-static       show static_info
-temp         show temperature_info
-temperature  show_temperature_info
-fast         show fast_info
-param        show param_info
-clock        show clock_info
-all          show all infos structures
```

## usage information
if no command line options are given information on usage is printed in addition to the static info of all TDCs.

# Programming Language
This example would work well in Python but we need this as a stand alone executable. Therefore we use this as an example on how to use the TDC in Golang.

While it seems to be reasonably easy to create C bindings for Golang by hand, it might be useful to autogenerate the interface using [SWIG](http://www.swig.org/) as we soon will also need support for c# and Python which are both supported by SWIG.

As for the other projects the code readability and simple structure of the project is important as it shall serve as a source code example to our users.

# Priority
This project has the same priority as the readout tool. Select an order and then do one after the other, not in parallel.

**Comment by Bassem-Ramzy** [comment]
Go native struct printf

```Go
type xhptdc8_manager_init_parameters struct {
	version            int
	buffer_size        int64
	variant            int
	device_type        int
	dma_read_delay     int
	multiboard         bool
	use_ext_clock      bool
	ignore_calibration bool
}

func main() {
    var parms xhptdc8_manager_init_parameters
    fmt.Printf("%+v", parms)
}
```

Output is 
```
{version:0 buffer_size:0 variant:0 device_type:0 dma_read_delay:0 
multiboard:false use_ext_clock:false ignore_calibration:false}
```

I'm not a big fan of that output presentation
[Here is a link](https://www.geeksforgeeks.org/printing-struct-variables-in-golang/) to native go printf of struct

**Comment by Bassem-Ramzy** [comment]
Warning while generating .go file from the interface using SWIG
```
C:\Users\basse\source\repos\xhptdc8_babel\dummy\golang\..\..\lib\include\xHPTDC8_interface.h(245) : Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
```
Because of the `TDCHit.type`

**Comment by sulimma** [comment]
Please do research on the consequences of this. Try whether it can be named "type" anyway in this context.
If not, it should be possible to use a different name for the Go interface. Like "hit_type".

**Comment by Bassem-Ramzy** [comment]
> Go native struct printf
> 
> ```go
> type xhptdc8_manager_init_parameters struct {
> 	version            int
> 	buffer_size        int64
> 	variant            int
> 	device_type        int
> 	dma_read_delay     int
> 	multiboard         bool
> 	use_ext_clock      bool
> 	ignore_calibration bool
> }
> 
> func main() {
>     var parms xhptdc8_manager_init_parameters
>     fmt.Printf("%+v", parms)
> }
> ```
> 
> Output is
> 
> ```
> {version:0 buffer_size:0 variant:0 device_type:0 dma_read_delay:0 
> multiboard:false use_ext_clock:false ignore_calibration:false}
> ```
> 
> I'm not a big fan of that output presentation
> [Here is a link](https://www.geeksforgeeks.org/printing-struct-variables-in-golang/) to native go printf of struct

A better presentation is using `json.MarshalIndent`:
```Go
package main
import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"syscall"
	"time"
	"unsafe"
)
type xhptdc8_manager_init_parameters struct {
	Version            int
	Buffer_size        int64
	Bariant            int
	Device_type        int
	Dma_read_delay     int
	Multiboard         bool
	Use_ext_clock      bool
	Ignore_calibration bool
	Name               string
}
func main() {
	parms := &xhptdc8_manager_init_parameters{
		Name:           "Main",
		Version:        5,
		Buffer_size:    6,
		Bariant:        7,
		Device_type:    8,
		Dma_read_delay: 9,
	}
	out1, err1 := json.MarshalIndent(parms, "", "  ")
	if err1 != nil {
		log.Println(err1)
		os.Exit(1)
	}
	fmt.Println(string(out1))
}
```

Output is:
```
{
  "Version": 5,
  "Buffer_size": 6,
  "Bariant": 7,
  "Device_type": 8,
  "Dma_read_delay": 9,
  "Multiboard": false,
  "Use_ext_clock": false,
  "Ignore_calibration": false,
  "Name": "Main"
}
```

With the following prerequisites:
1. struct member name starts with a _Capital Letter_. Defining the structs from our interface.h should take this into consideration.

**Comment by Bassem-Ramzy** [comment]
> Please do research on the consequences of this. Try whether it can be named "type" anyway in this context.
> If not, it should be possible to use a different name for the Go interface. Like "hit_type".

Found a solution 
Add to SWIG interface file the following:
```
%rename(Type) type;
```
or the following to match the fullname
```
%rename(Type, fullname=1) type;
```
It renames the variable in generated GoLang to `Type`

**Comment by Bassem-Ramzy** [comment]
Evaluation for research on using SWIG for wrapping C++ to Go:

## Findings 
1. There is no much resources about wrapping structures directly from header files, and renaming the structure members (e.g. TDCHit::type).
2. Steps are a bit complicated, using different flags, supporting different special cases.

## Issues

Stuck in the following issues with partial/no solution found:
### SWIG Done
For SWIG interface:
```SWIG
%module dummy
%{
#include "../../lib/include/xHPTDC8_interface.h"
%}
%include "../../lib/include/xHPTDC8_interface.h"
```
And SWIG command
```
swig -go -intgosize 64 xhptdc8_interface.i
```
### 1) Get the wrapped structure in Go and use it, in _a simple and straightforward way_.
- I only have struct interface but not the struct itself to be used in a simple readable way.
- I also have interface functions implemented, obviously linked to a generated .c file that is hard to read.
```Go
type TDCHit interface {
	Swigcptr() uintptr
	SwigIsTDCHit()
	SetTime(arg2 int64)
	GetTime() (_swig_ret int64)
	SetChannel(arg2 byte)
	GetChannel() (_swig_ret byte)
	SetType(arg2 byte)
	GetType() (_swig_ret byte)
	SetBin(arg2 uint16)
	GetBin() (_swig_ret uint16)
}
func (arg1 SwigcptrTDCHit) SetTime(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_TDCHit_time_set_dummy_3800a4861a50ab3b(C.uintptr_t(_swig_i_0), C.swig_type_3(_swig_i_1))
}
```
And the corresponding .c wrapper code:
```C
void _wrap_TDCHit_time_set_dummy_3800a4861a50ab3b(TDCHit *_swig_go_0, long long _swig_go_1) {
  TDCHit *arg1 = (TDCHit *) 0 ;
  long long arg2 ;
  
  arg1 = *(TDCHit **)&_swig_go_0; 
  arg2 = (long long)_swig_go_1; 
  
  if (arg1) (arg1)->time = arg2;
  
}
```
### 2) Renaming all structure members to start in upper case
This is in order to be recognized by `MarshalIndent` as described above

Tried many solutions with no effect:
```SWIG
%rename(Type, fullname=1) TDCHit::type;
%rename("%(firstlowercase)s") "*::type";
%rename("%(firstlowercase)s") "*::type";
%rename("%(firstuppercase)s") "*::xhptdc8_*::.*"; 
```
As a matter of fact, I still don't see a struct in go, but the c wrapper functions are like
```C
_wrap_TDCHit_time_get_dummy_1cf80e89caa10395
```
But when we use 
```SWIG
%rename("%(firstuppercase)s") ""; 
```
this function is like
```C
_wrap_TDCHit_Time_set_dummy_e7717e02c207c06e
```
with _Time_ starts in capital letter
 
### 3) Postfix by SWIG
For having a readable simple code, my first impression is that we need to delete the postfix added by the generator in every function name, e.g. delete _e7717e02c207c06e_ in __wrap_TDCHit_time_get_dummy_e7717e02c207c06e_ to be __wrap_TDCHit_time_get_dummy_.
Although it's simple, but I'm not sure of the impact of the code, for instance, it shall be updated in .c wrapper as well.
The postfix  is automatically generated every time we run swig, so, it should be removed manually every time, or there should be a flag in swig not to use it.

### 4) Not sure what .c generated file is used for
Obviously, this needs investigation, but didn't find it during my quick corresponding research

## Conclusion
The more code we need to wrap, the more need of SWIG is. The more code we have the more complicated SWIG gets. 
Since we have only 20+ functions, and 10+ structures in our driver, with a very low likelihood to add much functions and structures, I see it like "killing a fly with a cannon". 
Accordingly, it is much **_easier_ and _time-saving_ and _readable_ to write them all manually** (just copy and paste and update).

**Comment by Bassem-Ramzy** [comment]
@sulimma: In section _choosing what information to print_, how the user will determine which device he/she wants to display the relevant information for?  Or, the info will be displayed for all devices?

**Comment by sulimma** [comment]
See above, subsection "choosing which TDC to print"

**Comment by Bassem-Ramzy** [comment]
> See above, subsection "choosing which TDC to print"

Yep, got it 
The serial number is got from: static_info->board_serial? It seems one serial per board.

**Comment by sulimma** [comment]
Yes.

**Comment by Bassem-Ramzy** [comment]
We need a sample serial for Dummy Library, could you please provide one?

Also, regarding to
> By default all xHPTDC8 are listed, sorted by serial number.

Where can we get that list from?

**Comment by Bassem-Ramzy** [comment]
@sulimma 
I reached the following structures output so far, any comment? Should we display boolean as Yes/No (True/False) instead of 0/1?

```
Static Information 'xhptdc8_static_info'
{
  "Size": 80,
  "Version": 1,
  "Board_id": 10,
  "Driver_revision": 18,
  "Driver_build_revision": 1,
  "Firmware_revision": 0,
  "Board_revision": 0,
  "Board_configuration": 0,
  "Subversion_revision": 0,
  "Chip_id": [
    0,
    0
  ],
  "Board_serial": 0,
  "Flash_serial_high": 0,
  "Flash_serial_low": 0,
  "Flash_valid": 0,
  "Calibration_date": "2020-01-01 00:00"
}
Clock Information 'xhptdc8_param_info'
{
  "Size": 20,
  "Version": 1,
  "Cdce_locked": 0,
  "Cdce_version": 0,
  "Use_ext_clock": 0,
  "Fpga_locked": 0
}
Fast Information 'xhptdc8_fast_info'
{
  "Size": 32,
  "Version": 2,
  "Fpga_rpm": 0,
  "Alerts": 0,
  "Pcie_pwr_mgmt": 0,
  "Pcie_link_width": 1,
  "Pcie_max_payload": 0,
  "State": 0
}
Param Information 'Xhptdc8_param_info'
{
  "Size": 32,
  "Version": 2,
  "Binsize": 0,
  "Channels": 8,
  "Channel_mask": 0,
  "Total_buffer": 0
}
Temprature Information 'xhptdc8_temperature_info'
{
  "Tdc": [
    46.3,
    46.3
  ],
  "Fpga": 65
}
End of program
```

By the way, this is default init parameters, might be needed as well for initialization using YAML
```
Default Initialization Parameters 'xhptdc8_manager_init_parameters'
{
  "Version": 1,
  "Buffer_size": 0,
  "Variant": 0,
  "Device_type": 12,
  "Dma_read_delay": 250,
  "Multiboard": 0,
  "Use_ext_clock": 0,
  "Ignore_calibration": 0
}
```

**Comment by sulimma** [comment]
There is an API function that returns the number of devices.
Then you can use the get_xxx_info() functions to get the details for each of them.

**Comment by sulimma** [comment]
The output is good, but please use the format from the spec for the first line:
```
fast_info of xHPTDC8 serial 21.108 at index 1:
```

**Comment by Bassem-Ramzy** [comment]
Go code dynamically linked to the driver is done, tested (on the Dummy library) and pushed, with the following outputs:

**No TDC nor Flags are passed in command line**
`>xhptdc8_info.exe`
- All xHPTDC8 are listed, sorted by serial number
- About (usage) is displayed
- Static info of all TDCs is displayed.
```
-----------------------------------------------------------------------------
               xHPTDC8 Information Utility Application
-----------------------------------------------------------------------------

Installed Devices Serials for 1 TDC(s):
1 ) index: 0 xHPTDC8 serial 21.108

Info: No device selected.

About the application
Command:
  xhptdc8_info.exe [TDC] [Flags]
Usage:
  [TDC]   is either an integer as the index of the TDC, or a serial number of the TDC
  [Flags] Can be one or more of the following flags:
          -tdc=[TDC]    is either an integer as the index of the TDC, or a serial number of the TDC
          -v            show size and version information for all selected structures
          -static       show static_info
          -temp         show temperature_info
          -temperature  show_temperature_info
          -fast         show fast_info
          -param        show param_info
          -clock        show clock_info
          -all          show all infos structures
          -h            show this help



Static Information of all TDC(s):
static_info of xHPTDC8 serial 21.108 at index 0
{
  "Board_id": 10,
  "Driver_revision": 18,
  "Driver_build_revision": 1,
  "Firmware_revision": 0,
  "Board_revision": 0,
  "Board_configuration": 0,
  "Subversion_revision": 0,
  "Chip_id": [
    0,
    0
  ],
  "Board_serial": 21.108,
  "Flash_serial_high": 0,
  "Flash_serial_low": 0,
  "Flash_valid": 0,
  "Calibration_date": "2020-01-01 00:00"
}

-----------------------------------------------------------------------------
                          End of Application
-----------------------------------------------------------------------------
```

**TDC is passed with no flag**
`>xhptdc8_info.exe -tdc=0`
- All xHPTDC8 are listed, sorted by serial number.
- Only static info of the selected board is displayed.
```
-----------------------------------------------------------------------------
               xHPTDC8 Information Utility Application
-----------------------------------------------------------------------------

Installed Devices Serials for 1 TDC(s):
1 ) index: 0 xHPTDC8 serial 21.108

static_info of xHPTDC8 serial 21.108 at index 0
{
  "Size": 80,
  "Version": 1,
  "Board_id": 10,
  "Driver_revision": 18,
  "Driver_build_revision": 1,
  "Firmware_revision": 0,
  "Board_revision": 0,
  "Board_configuration": 0,
  "Subversion_revision": 0,
  "Chip_id": [
    0,
    0
  ],
  "Board_serial": 21.108,
  "Flash_serial_high": 0,
  "Flash_serial_low": 0,
  "Flash_valid": 0,
  "Calibration_date": "2020-01-01 00:00"
}
-----------------------------------------------------------------------------
                          End of Application
-----------------------------------------------------------------------------
```

**TDC and fast are both specified**
`xhptdc8_info.exe -tdc=21.108 -fast`
- All xHPTDC8 are listed, sorted by serial number.
- Only fast info of the selected board is displayed.
```
-----------------------------------------------------------------------------
               xHPTDC8 Information Utility Application
-----------------------------------------------------------------------------

Installed Devices Serials for 1 TDC(s):
1 ) index: 0 xHPTDC8 serial 21.108

fast_info of xHPTDC8 serial 21.108 at index 0
{
  "Size": 32,
  "Version": 2,
  "Fpga_rpm": 0,
  "Alerts": 0,
  "Pcie_pwr_mgmt": 0,
  "Pcie_link_width": 1,
  "Pcie_max_payload": 0,
  "State": 0
}
-----------------------------------------------------------------------------
                          End of Application
-----------------------------------------------------------------------------
```

**TDC (index) and fast flag are both passed, with -v**
`xhptdc8_info.exe -tdc=0 -fast -v`
- All xHPTDC8 are listed, sorted by serial number.
- Only fast info of the selected board is displayed.
- No version info/size are displayed
```
-----------------------------------------------------------------------------
               xHPTDC8 Information Utility Application
-----------------------------------------------------------------------------

Installed Devices Serials for 1 TDC(s):
1 ) index: 0 xHPTDC8 serial 21.108

fast_info of xHPTDC8 serial 21.108 at index 0
{
  "Fpga_rpm": 0,
  "Alerts": 0,
  "Pcie_pwr_mgmt": 0,
  "Pcie_link_width": 1,
  "Pcie_max_payload": 0,
  "State": 0
}
-----------------------------------------------------------------------------
                          End of Application
-----------------------------------------------------------------------------
```

**TDC (index) and -all flag are passed**
`xhptdc8_info.exe -tdc=0 -all`
- All xHPTDC8 are listed, sorted by serial number.
- All info of the selected board are displayed.
```
-----------------------------------------------------------------------------
               xHPTDC8 Information Utility Application
-----------------------------------------------------------------------------

Installed Devices Serials for 1 TDC(s):
1 ) index: 0 xHPTDC8 serial 21.108

clock_info of xHPTDC8 serial 21.108 at index 0
{
  "Size": 20,
  "Version": 1,
  "Cdce_locked": 0,
  "Cdce_version": 0,
  "Use_ext_clock": 0,
  "Fpga_locked": 0
}
fast_info of xHPTDC8 serial 21.108 at index 0
{
  "Size": 32,
  "Version": 2,
  "Fpga_rpm": 0,
  "Alerts": 0,
  "Pcie_pwr_mgmt": 0,
  "Pcie_link_width": 1,
  "Pcie_max_payload": 0,
  "State": 0
}
param_info of xHPTDC8 serial 21.108 at index 0
{
  "Size": 32,
  "Version": 2,
  "Binsize": 0,
  "Channels": 8,
  "Channel_mask": 0,
  "Total_buffer": 0
}
static_info of xHPTDC8 serial 21.108 at index 0
{
  "Size": 80,
  "Version": 1,
  "Board_id": 10,
  "Driver_revision": 18,
  "Driver_build_revision": 1,
  "Firmware_revision": 0,
  "Board_revision": 0,
  "Board_configuration": 0,
  "Subversion_revision": 0,
  "Chip_id": [
    0,
    0
  ],
  "Board_serial": 21.108,
  "Flash_serial_high": 0,
  "Flash_serial_low": 0,
  "Flash_valid": 0,
  "Calibration_date": "2020-01-01 00:00"
}
temperature_info of xHPTDC8 serial 21.108 at index 0
{
  "Size": 20,
  "Version": 3,
  "Tdc": [
    46.3,
    46.3
  ],
  "Fpga": 65
}
-----------------------------------------------------------------------------
                          End of Application
-----------------------------------------------------------------------------
```
@sulimma for your comments & feedback.

**Comment by sulimma** [comment]
Please invert the -v switch. Version and size are only specified if "-v" is added. Otherwise they are omitted.

**Comment by Bassem-Ramzy** [comment]
> Please invert the -v switch. Version and size are only specified if "-v" is added. Otherwise they are omitted.

Sorry, I swapped it, fix is going to be pushed soon

**Comment by sulimma** [comment]
#48 made it clear that the tool does not operate to the speficcation given in this issue. Please fix.

If there is at least one command line switch, only the selected structures are printed.
Note the plural in "structures".

However, in the wiki you differentiate between "-all", "one structure" or "one structure and -v".
https://github.com/cronologic-de/xhptdc8_babel/wiki/using_info_tool
That is not the intended behaviour.

The idea was that the user can list any combination of structures or -v and then everything that was specified is printed out.
There is no need for special cases in the documentation. Please simplify the wiki accordingly.

The code should:

add "-static" to the set of print methods to run.
clear the set of methods whenever the first flag specifying a print option is found on the command line
add whatever options are found on the command line to the set of print methods
Independently (orthogonally) from that

the set of TDCs to process is set to all TDCs
if the first command line option is not a flag, the TDC it specified is added to the set of TDCs to process
if a flag "-tdc" is encountered, the TDC is added to the set of boards to be processed
loop over the set of tdcs and call each print method from the set of print methods on each of these

**Comment by Bassem-Ramzy** [comment]
@sulimma 
> add "-static" to the set of print methods to run.
clear the set of methods whenever the first flag specifying a print option is found on the command line
add whatever options are found on the command line to the set of print methods

OK

> Independently (orthogonally) from that
the set of TDCs to process is set to all TDCs

OK
> if the first command line option is not a flag, the TDC it specified is added to the set of TDCs to process

It should be passed with `-tdc=[TDC]` as per a recent [update](#48). 
   _[TDC]   is either an integer as the index of the TDC, or a serial number of the TDC
		  passed as a value of the flag -tdc, i.e. -tdc=[TDC]_
Currently, and based on the `flag` Go package, a value in command line is accepted _only_ after either `-<print option flag>` or `-tdc`.

> if a flag "-tdc" is encountered, the TDC is added to the set of boards to be processed

I believe we do similar to the print flags, i.e.
_clear the set of TDCs whenever the first flag specifying a TDC is found on the command line_
Right?

> loop over the set of tdcs and call each print method from the set of print methods on each of these

OK
