### ISSUE TITLE
Update Dummy Library with finalized API when available

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#2]
There will be fixes and small API changes with the final driver release. These must be ported to the dummy library.
See issue #1.

**Comment by Bassem-Ramzy** [comment]
Dummy Library builds successfully with latest versions of xHPTDC8_interface.h (updated 19 March), and crono_interface.h.
github action that builds Dummy Library is triggered as well when ./lib/include/** changes, and will send failure email in case the build failed
Any new fixes will be reported in new issues
