### ISSUE TITLE
New API changes and new user Guide

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#25]
There is a new user guide in the results of this GitHub action:
https://github.com/cronologic-de/ug_xtdc_timetagger_xhptdc/actions/runs/733831291

There have been some API changes. Please work them into the dummy library.

I am going to send you the header file from the other developers. They did not merge your comments yet so please do merge the API changes into the cleaned up header and provide the resulting file. Provide the result to Andreas.

## changes to the API
* added adc_channel to config
* renamed threshold to trigger_threshold
* removed index 9 from trigger_threshold
* fixed veto_mode to int 
* changed interface to xhpt8_init() to return pointer to manager object
* gating block negate has opposite polarity compared to old documentation. Comments in .h have been wrong.

## UG only
* changed grouping_configuration.enable from bool to crono_bool_t

**Comment by Bassem-Ramzy** [comment]
All updates are applied
Still pending:
1. User Guide updates for xhptdc8_write_user_flash & xhptdc8_read_user_flash.
2. User Guide updates for xhptdc8_init: return in case of failure, return type (_xhptdc8_manager_ in .h & _xhptdc8_manager*_ in UG)

**Comment by Bassem-Ramzy** [comment]
All is good as per the [latest user guide](https://github.com/cronologic-de/ug_xtdc_timetagger_xhptdc/actions/runs/744553277)
