### ISSUE TITLE
Utility function get_all_error_messages

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#26]
The driver function get_last_error_message() needs to be provided with an index that selects the manager or one of the boards. (See new user guide).

That can be inconvenient. Please provide a method  that returns the error messages from all boards. In the format:
`"index, error_code, error_message\n"`
For example:
```CSV
-1, 5, "illegal argument"
0, 0, "OK"
````

The method shall have two boolean parameters which are false as default:
* `include_ok` outputs a line even if the board or the manager has no error
* `fixed_length` outputs a line for 8 boards, even if there are less boards in the system 

This issue has low priority

**Comment by Bassem-Ramzy** [comment]
@sulimma. I have the following questions:

1. In Dummy Library (based on interface.h) there is no function that returns both the _last_ error_code and _last_ error_message. How to get the _last error code_? 
2. For boards don't exist in the system: if fixed_length=true; xhptdc8_get_last_error_message should return error that the board index is invalid, should we display this error? 
3. In case the function itself generated an error, e.g. when calling xhptdc8_count_devices, it will return a pointer to "Internal Error", and not a list of boards errors. OK?
4. Should the error message be enclosed within " (double quotes)? Or it just starts after the comma and ends with a new line or NULL?

**Comment by sulimma** [comment]
1. Most functions return an error code. If you get an error code that is different from *_OK you can use "get_last_error_message" to retrieve the human readable error message for that code. I did not think about that. Do not output any error codes for this function.
2. For fixed length you should not call *_get_last_error_message() for boards that do not exist. Instead return "board does not exist". 
3. I would see internal errors in this function in the same domain as the manager, -1. We could distinguish the utility library from the manager by using -2.
I would prefer that the caller does not need to check for the length of the result if it already knows the number of boards and tries to loop over them.
So I suggest that you return 
```CSV
-2, "count_devices() returned error 'xyz some error' in get_all_error_messages()"
0, "could not retrieve error message"
```
The last line is repeated for 8 indexes if you don't know the number of boards in the system or if fixed_length is specified. Otherwise it is given for the number of boards in the system.
4. According to RFC 4180 any fields with ',' or '"' must be put into double quotes, otherwise each field can be optionally put into quotation marks. I suggest that we put the error message in double quotes to be on the safe side.

**Comment by Bassem-Ramzy** [comment]
OK, thanks.
I'm pushing the code, with the function signature as following:
```C
const char* xhptdc8_get_all_error_messages(xhptdc8_manager hMgr, crono_bool_t include_ok, crono_bool_t fixed_length)
```
hMgr is passed to it from caller.

**Comment by Bassem-Ramzy** [comment]
With include_ok=true, fixed_length=true
Normal output is:
```CMD
0, "OK"
1, "Board does not exist"
2, "Board does not exist"
3, "Board does not exist"
4, "Board does not exist"
5, "Board does not exist"
6, "Board does not exist"
7, "Board does not exist"
```

Error in arguments:
```CMD
-1, "Invalid arguments"
0, "Manager is invalid!"
1, "Board does not exist"
2, "Board does not exist"
3, "Board does not exist"
4, "Board does not exist"
5, "Board does not exist"
6, "Board does not exist"
7, "Board does not exist"
```

For error in device_count (null error message)
```CMD
-2, "count_devices() returned error <17> (null) in get_all_error_messages()."
0, "Could not retrieve error message."
1, "Could not retrieve error message."
2, "Could not retrieve error message."
3, "Could not retrieve error message."
4, "Could not retrieve error message."
5, "Could not retrieve error message."
6, "Could not retrieve error message."
7, "Could not retrieve error message."
```

**Comment by sulimma** [comment]
Please document the function in the Readme.md of 
https://github.com/cronologic-de/xhptdc8_babel/tree/main/util
