### ISSUE TITLE
Info-Tool Details

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#28]
A)
Please move the Info-Tool to /go/info/

B)
Please add a commandline switch -d that only outputs the requested data in JSON format without header, footer, etc. 
This is intended to be called when the output is processed by other software or piped into a file.

C)
Please write a section in the README.md of the info tool about how to use our driver with go: The upper case struct members, the alternate header file, the linker flags and the location of .lib and .dll at run and compile time.

**Comment by Bassem-Ramzy** [comment]
B)

For 
```CMD
.\xhptdc8_info.exe -d -tdc=0 -temp
```

We get:
```JSON
temperature_info of xHPTDC8 serial 21.108 at index 0 :
{
  "Tdc": [
    46.3,
    46.3
  ],
  "Fpga": 65
}
```
------

And for:
```CMD
.\xhptdc8_info.exe -tdc=0 -temp
```

We get:
```JSON
-----------------------------------------------------------------------------
               xHPTDC8 Information Utility Application
-----------------------------------------------------------------------------

Installed Devices Serials for 1 TDC(s):
1 ) index: 0 xHPTDC8 serial 21.108

temperature_info of xHPTDC8 serial 21.108 at index 0 :
{
  "Tdc": [
    46.3,
    46.3
  ],
  "Fpga": 65
}
-----------------------------------------------------------------------------
                          End of Application
-----------------------------------------------------------------------------
```

-----

And for:
```CMD
.\xhptdc8_info.exe -tdc=0 -temp -v
```

We get:
```JSON
-----------------------------------------------------------------------------
               xHPTDC8 Information Utility Application
-----------------------------------------------------------------------------

Installed Devices Serials for 1 TDC(s):
1 ) index: 0 xHPTDC8 serial 21.108

temperature_info of xHPTDC8 serial 21.108 at index 0 :
{
  "Size": 20,
  "Version": 3,
  "Tdc": [
    46.3,
    46.3
  ],
  "Fpga": 65
}
-----------------------------------------------------------------------------
                          End of Application
-----------------------------------------------------------------------------
```


@sulimma Right?

**Comment by sulimma** [comment]
The text line will disturb the parser. Unfortunatly JSON does not support comments.
Options are:
A)
move it into a pseudo comment that is JSON compliant:
```JSON
"_comment" : "temperature_info of xHPTDC8 serial 21.108 at index 0"
{
  "Size": 20, 
```

B)
remove the text and wrap and provide only the index of the TDC as reference:
```JSON
{
  "0": {
     "Size: 20,
```

C) 
Just remove the text line.


I am in favor of option C). 
Option -d is intended for machines to get data back from calling the tool. The calling function knows the index.

**Comment by Bassem-Ramzy** [comment]
I will go with C as well

Results are now as following:

For 
```CMD
.\xhptdc8_info.exe -d -tdc=0 -temp
```

We get:
```JSON
{
  "tdc": [
    46.3,
    46.3
  ],
  "fpga": 65
}
```
---
For 
```
.\xhptdc8_info.exe -tdc=0 -temp
```

We get:
```JSON
-----------------------------------------------------------------------------
               xHPTDC8 Information Utility Application
-----------------------------------------------------------------------------

Installed Devices Serials for 1 TDC(s):
1 ) index: 0 xHPTDC8 serial 21.108

temperature_info of xHPTDC8 serial 21.108 at index 0
{
  "tdc": [
    46.3,
    46.3
  ],
  "fpga": 65
}
-----------------------------------------------------------------------------
                          End of Application
-----------------------------------------------------------------------------
```
---
For 
```CMD
.\xhptdc8_info.exe -tdc=0 -temp -v
```

We get:
```JSON
-----------------------------------------------------------------------------
               xHPTDC8 Information Utility Application
-----------------------------------------------------------------------------

Installed Devices Serials for 1 TDC(s):
1 ) index: 0 xHPTDC8 serial 21.108

temperature_info of xHPTDC8 serial 21.108 at index 0
{
  "size": 20,
  "version": 3,
  "tdc": [
    46.3,
    46.3
  ],
  "fpga": 65
}
-----------------------------------------------------------------------------
                          End of Application
-----------------------------------------------------------------------------
```
@sulimma updated also so that variables start in small letters as per [Issue #30]

**Comment by sulimma** [comment]
Perfect. Please provide a binary to @crono-melissa so that she can test it with real hardware.

**Comment by Bassem-Ramzy** [comment]
@crono-melissa 
I've pushed the latest version of the info tool to github
You will find the following:
1. exe [here](https://github.com/cronologic-de/xhptdc8_babel/tree/main/go/bin/x64); just grab it in the folder of the driver dll (xhptdc8_driver_64.dll) or vice versa.
2. All commands and examples are found on [wiki page](https://github.com/cronologic-de/xhptdc8_babel/wiki/using_info_tool).

I could only test on the dummy library with only one device supported.
Please test it on real driver and create issues on github with any bug
Thanks,

**Comment by Bassem-Ramzy** [comment]
Point C) is done, except that we don't need "alternate header file" any more.
