### ISSUE TITLE
Info tool output with lower case struct members

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#30]
Except for go all languages using the tool use lower case struct members. Therefore the JSON output should also be in lower case.

I guess the easiest way to accomplish that is to get the result from JSON.MarshallIndent() and the convert the whole string to lower case.

We need to check whether there are any strings returned that will be broken by this approach..

**Comment by sulimma** [comment]
This is done, isn't it?

**Comment by Bassem-Ramzy** [comment]
> This is done, isn't it?

Done in the cgo code, still needs to be updated in Go dynamic link code

**Comment by sulimma** [comment]
Get rid of the dynamic link code. 
It is archived in the version history but should not confuse customers. Just present the most simple solution that we found.
