### ISSUE TITLE
Add Info-Tool Binary to the Driver installer

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#32]
This will be done by Dennis.

@Bassem-Ramzy:
Please work with Dennis on a way to automatically get the latest binary to the installer.
You could have a github action that compiles the binary upon push and the Dennis uses his build script to download the asset.

Or any other way that is convenient and reliable.

**Comment by Bassem-Ramzy** [comment]
Building 368 GOARCH causes errors: looks related to package visibility:
```CMD
xhptdc8_info_display\utilities.go:20:34: undefined: Crono_int_t
.\info_aux.go:51:13: undefined: xhptdc8_info_display.Init_globals
.\info_aux.go:56:20: undefined: xhptdc8_info_display.Get_devices_count
.\
```
Working on that

**Comment by Bassem-Ramzy** [comment]
I'm getting a weird error from go compiler when building it for x86, after researching a lot with many trials, I submitted an [issue on go](https://github.com/golang/go/issues/45579), hope to get a quick resolution.
I believe there is some settings that I don't know.

**Comment by Bassem-Ramzy** [comment]
And, 
https://stackoverflow.com/questions/67108696/go-build-error-build-constraints-exclude-all-go-files-when-goarch-386-with-imp

**Comment by Bassem-Ramzy** [comment]
xhptdc8_info.exe & xhptdc8_info_64.exe are automatically built using github action and pushed to \go\info\bin corresponding sub-folder
