### ISSUE TITLE
Add *_software_trigger() to dummy library

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#35]
'''C
int xhptdc8_software_trigger(xhptdc8_manager hMgr, int index)
'''

In the dummy library this function does nothing except returning XHPTDC8_OK.

With real hardware this issues a trigger event for one clock cycle that can be used as a trigger source for the TiGer and Gating blocks.

**Comment by Bassem-Ramzy** [comment]
Done adding in a previous push
