### ISSUE TITLE
Changes in header file

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#36]
@ahofmann75 did cosmetic changes to the header file.

@Bassem-Ramzy :
This should not change anything for compilation, but please check whether the dummy lib still compiles.

(Or is there any automatic compile on push vie github actions?)

**Comment by Bassem-Ramzy** [comment]
Yes, it compiles successfully 
[Last automatic build](https://github.com/cronologic-de/xhptdc8_babel/actions/runs/767652081)
