### ISSUE TITLE
What do you think of Rust and Go?

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#40]
You have been using Golang and Rust for two small projects now. 
What was your experience, both with the language and the compiler.

It is said about Rust that it is difficult for beginners to grasp the concept of variable ownership.
How was that for you?
It is also said to provide excellent compiler error output. Do you second that?

What else did you notice?

**Comment by Bassem-Ramzy** [comment]
**Rust:**
1. Really annoying to _fully_ cover the ownership concept, however, many articles illustrate it pretty well so it could be "memorized" or resolved easily. But for a C++ backgrounder, it's an un-needed complication. 
2. The ownership is fundamental for the "excellent compiler error output", I think this compiler might be helpful to developers who are not experienced enough to either write a robust code or debug their code efficiently. For me, almost all the errors/warnings I got from the compiler were related to lack of knowledge of the ownership & mutation.
3. Using Rust to call C FFI makes us obliged to deal with all the ownership related complications that the normal program might not face at all: ownership, pass by reference, mutation, arrays/vectors/box, stack and heap, data conversion, data type cast, unsafe, pointers & address, and the combination of them on one function.
3. Easier in integration with C code/library than Go.
4. Crate concept and the libraries availability are good.
5. Apart from the ownership concept, it is less confusing than Go.
6. The Result & Option features of the language look strong _wrappers_.
7. Overall coding is less readable and more complex than Go.

**Comment by sulimma** [comment]
The hurdles introduced with the ownership concept are intended to avoid memory management errors (and improve performance). We have a fair share of memory errors in our projects.

Do you think that it might be worthwhile to learn Rust until we fully grasp these concecpts and then benefit from less errors, especially with multithreading?
Or could we just as well write our projects in C++?

**Comment by Bassem-Ramzy** [comment]
Rust _ownership_ is the same challenge the beginner faces as C _pointers_, so they are equal in annoyance anyways.
I believe that if memory handling is _significantly a challenge_ in our type of projects, we can go Rust. Assuming it has, at least, the same capabilities of C regarding to pointers, and flexibility building libraries in cross-platform. 
Let's bear in mind the conversion of code from C++ to Rust as well.
