### ISSUE TITLE
Changes in the API

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#5]
The folling will be removed from the API
XHPTDC8_TDC_MODE_GROUPED  
XHPTDC8_TDC_MODE_CONTINUOUS 
xhptdc8_device_configuration.tdc_mode 

The following shall be added
xhptdc8_grouping_configuration.enabel = false 

xhptdc8_device_configuration.tdc_trigger_offset 
renamed to
xhptdc8_device_configuration.thresholds

All defines
XHPTDC8_DC_OFFSET_*
renamed to 
XHPTDC8_THRESHOLD_*

**Comment by Bassem-Ramzy** [comment]
- xhptdc8_device_state_to_str() is updated in /lib/include/xHPTDC8_interface.h, with the next commit
- bool enabled = false; is added to xhptdc8_grouping_configuration in /lib/include/xHPTDC8_interface.h, with the next commit
- All defines
XHPTDC8_DC_OFFSET_*
renamed to
XHPTDC8_THRESHOLD_*
updated in /lib/include/xHPTDC8_interface.h, with the next commit
- tdc_trigger_offset updated to be thresholds in /lib/include/xHPTDC8_interface.h, with the next commit

**Comment by sulimma** [comment]
Sorry for chaos, but xhptdc8_device_state_to_str(int state) is correct.
Please change it back.
The functions without _to_ do not take a parameter.

**Comment by Bassem-Ramzy** [comment]
Done, and committed

**Comment by Bassem-Ramzy** [comment]
tdc_mode updates are applied and committed

**Comment by Bassem-Ramzy** [comment]
All are applied and committed
