### ISSUE TITLE
xhptdc8_readout fails silently

### ISSUE THREAD

**Issue by ahofmann75** [cronologic-de/xhptdc8_babel#50]
xhptdc8_readout does not produce any output:
```
PS C:\Users\andreas\Documents\GitHub\xhptdc8_babel\rust\bin\x64> ls

    Directory: C:\Users\andreas\Documents\GitHub\xhptdc8_babel\rust\bin\x64

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        12/20/2021   1:11 PM          96768 xhptdc8_driver_64.dll
-a----        12/21/2021   1:44 PM        1891840 xhptdc8_readout_64.exe


PS C:\Users\andreas\Documents\GitHub\xhptdc8_babel\rust\bin\x64> .\xhptdc8_readout_64.exe
PS C:\Users\andreas\Documents\GitHub\xhptdc8_babel\rust\bin\x64>
```

**Comment by Bassem-Ramzy** [comment]
The main reason is the absence of a dependency DLL  `xhptdc8_util_64.dll`, which is a prerequisite as mentioned [in the documentation](https://github.com/cronologic-de/xhptdc8_babel/wiki/using_readout_tool#prerequisites)

Apparently, PowerShell doesn't display the relevant error, while the command does display the following message:
![image](https://user-images.githubusercontent.com/75851720/146939398-33e74433-4771-4f2a-9b01-c7e8b403950d.png)
