### ISSUE TITLE
Adjust file names of libraries

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#6]
The dummy library is intended to be a drop in replacement for development in projects where the code does not know that it is  using the dummy.
Therefore the filenames shall be the same for the dummy and the real driver.
Please follow the filename patterns in the [README.md](https://github.com/cronologic-de/xhptdc8_babel/tree/main/lib).

For example:
```bash
x64dummy/xhptdc8_driver_64.dll
```

**Comment by Bassem-Ramzy** [comment]
Updated in MSVS Project, PowerShell Script, YAML, and Wiki
