### ISSUE TITLE
bug in dummy random numbers

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#7]
`xhptdc8_read_hits()'
In non-gourping-mode, the same random number is applied to all hits. 
Instead, for each hit_index the a new random "normal" shall be computed.

Also, I suggest that you do not create a new copy of the random number generator all the time.
Just store a random number generator in a global static variable. This will be more efficient and create better random numbers.
The distribution can be created each time read_hits is called.

**Comment by Bassem-Ramzy** [comment]
Updated
